### ISSUE TITLE
Valkyrie::Persistence::Memory::MetadataAdapter doesn't support delete

### ISSUE THREAD

**Issue by awead** [escowles/vdemo#1]
The demo page has a delete called on the memory adapter, but that adapter doesn't support it. We could switch to the postgres adapter, or skip over deletes.

**Comment by escowles** [comment]
I think I just made a mistake and tried to call `delete` on the metadata adapter instead of the persister.  I just updated the Demo page — can you try it again?

**Comment by awead** [comment]
Yep, that's got it!
